
f = open("squares.h", "w")
f.write("""// generated by a python script
#pragma once

#include "square.h"

""")
for file in range(8):
    for rank in range(8):
        print(f"#define {chr(file + 65)}{rank + 1} (square_t){{.file = {file}, .rank = {rank}}}", file=f)
        
f.close()